# Generated by Django 3.2.10 on 2021-12-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(max_length=250, unique=True)),
                ('delivery_code', models.CharField(max_length=250, unique=True)),
                ('internal', models.BooleanField()),
                ('price', models.CharField(max_length=250, unique=True)),
                ('tax', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('weight', models.CharField(max_length=250, unique=True)),
                ('height', models.CharField(max_length=250, unique=True)),
                ('length', models.CharField(max_length=250, unique=True)),
                ('width', models.CharField(max_length=250, unique=True)),
                ('price', models.CharField(max_length=250, unique=True)),
                ('address_alias', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=250, unique=True)),
                ('height', models.CharField(max_length=250, unique=True)),
                ('length', models.CharField(max_length=250, unique=True)),
                ('time', models.TimeField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelHistoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=250, unique=True)),
                ('height', models.CharField(max_length=250, unique=True)),
                ('length', models.CharField(max_length=250, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelWarehouseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(max_length=250, unique=True)),
                ('address_alias', models.CharField(max_length=250, unique=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.address')),
            ],
        ),
    ]
