# Generated by Django 3.0.8 on 2021-12-16 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=250, unique=True)),
                ('national_id', models.CharField(max_length=250, unique=True)),
                ('address_alias', models.CharField(max_length=250, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, unique=True)),
                ('last_name', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=250, unique=True)),
                ('national_id', models.CharField(max_length=250, unique=True)),
                ('company_id', models.CharField(max_length=250, unique=True)),
                ('position', models.CharField(max_length=250, unique=True)),
                ('birthday', models.CharField(max_length=250, unique=True)),
                ('address_alias', models.CharField(max_length=250, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, unique=True)),
                ('last_name', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=250, unique=True)),
                ('national_id', models.CharField(max_length=250, unique=True)),
                ('birthday', models.CharField(max_length=250, unique=True)),
                ('address_alias', models.CharField(max_length=250, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, unique=True)),
                ('last_name', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=250, unique=True)),
                ('national_id', models.CharField(max_length=250, unique=True)),
                ('birthday', models.CharField(max_length=250, unique=True)),
                ('address_alias', models.CharField(max_length=250, unique=True)),
                ('vehicle_id', models.CharField(max_length=250, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CarrierCategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
